/** Die Modelle der API an einer Stelle, damit Seiten nur einen Pfad kennen. */
export {
  BAUMARTEN,
  EDIBILITIES,
  GEFAEHRDUNGEN,
  GROUPS,
  HAEUFIGKEITEN,
  SEASONS,
  FEATURE_KEYS,
  REAGENZIEN,
  LEVELS,
  TIER_BEST,
  TIER_WEAKEST,
} from './species';
export { COLORS, VISIBILITIES } from './entries';
export type {
  Color,
  Photo,
  Find,
  FindPatch,
  FindInput,
  GeoPolygon,
  SharedFind,
  Marker,
  MarkerPatch,
  MarkerInput,
  Page,
  Visibility,
  Zone,
  ZonePatch,
  ZoneInput,
  ZoneValue,
} from './entries';
export type {
  Species,
  SpeciesCatalogue,
  SpeciesBrief,
  BaeumeAusErfahrung,
  Betrifft,
  Baumart,
  Essbarkeit,
  Gefaehrdung,
  Group,
  Haeufigkeit,
  YearRange,
  SeasonOfYear,
  Marktfaehigkeit,
  Masse,
  Feature,
  FeatureKey,
  Source,
  Reagenz,
  Reagenzeintrag,
  SeasonCurveData,
  SeasonCurveBrief,
  Spanne,
  Level,
  Tag,
  Link,
  Confusable,
  Week,
} from './species';
